### ISSUE TITLE
NoNameClub definition duplication

### ISSUE THREAD

**Issue by dm3ch** [Prowlarr/Indexers#104]
There's two definitions for same site:
https://github.com/Prowlarr/Indexers/blob/master/definitions/v2/noname-club.yml
https://github.com/Prowlarr/Indexers/blob/master/definitions/v2/noname-clubl.yml

[AB#2287](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2287)

**Comment by bakerboy448** [comment]
Not a dupe

The L is the login one
