### ISSUE TITLE
[HD-Only] The definition deserve some improvements

### ISSUE THREAD

**Issue by hummingbirdy2** [Prowlarr/Indexers#132]
Hello,

I see some issue on the HD-Only definition:
- The [category 4 "Concert" (first one)](https://github.com/Prowlarr/Indexers/blob/a7d04e5cb0fad4d2cc585a6d24c320ddc55cb0b1/definitions/v1/hdonly.yml#L15) does not exist
- Category id 7 is declared two times, [the "Concert" (second)](https://github.com/Prowlarr/Indexers/blob/a7d04e5cb0fad4d2cc585a6d24c320ddc55cb0b1/definitions/v1/hdonly.yml#L19) should be with the id 9
- In order to make possible the search with the release year, replace [groupname](https://github.com/Prowlarr/Indexers/blob/a7d04e5cb0fad4d2cc585a6d24c320ddc55cb0b1/definitions/v1/hdonly.yml#L101) by `searchstr`. After that, the [info radarr](https://github.com/Prowlarr/Indexers/blob/a7d04e5cb0fad4d2cc585a6d24c320ddc55cb0b1/definitions/v1/hdonly.yml#L77) can be removed.

I test everything as custom definition, and works well: [custom definition file](https://pastebin.com/RpsyN4dR)

[AB#2572](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2572)

**Comment by bakerboy448** [comment]
If your custom def works - PRs welcome and encouraged :)

**Comment by hummingbirdy2** [comment]
This is a V1 definition, extra work has to be done to be V4 compatible ?

**Comment by bakerboy448** [comment]
Nah. They're all backwards compatible.

V1 is no longer maintained- so just add it as v2 (assuming we don't have a v4/v3 for it which I don't believe we do)
