### ISSUE TITLE
1337x Replace "-" removing the group

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Indexers#156]
https://github.com/Prowlarr/Indexers/blob/60215e1eb0d969b06d919e40044c044e91b1e027/definitions/v3/1337x.yml#L204

@garfield69
Any thoughts on the background or best way to handle this?

replace of - means no groups from 1337x for \*arrs

https://www.reddit.com/r/radarr/comments/tlwi2o/trash_guides_inconsistent_scoring_between_indexers/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

[AB#2843](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2843)

**Comment by garfield69** [comment]
>Any thoughts on the background

the reason stems from https://github.com/Jackett/Jackett/issues/11449

no ideas atm, I'll think on it.

**Comment by garfield69** [comment]
quick fix would be to add another replace to restore the dash for that group, as long as there are not too many others groups with dashes this would seem the simplest work around..
But if there are many groups impacted this way, then I don't see a solve, if 11449 is correct the dash removal has a purpose whose need overrides the occasional group name mangling, as far as I can tell.

**Comment by bakerboy448** [comment]
I mean it seems that replace will break every single group given every group and the naming standard is -Group.

I may have missed it, but I'm don't think I saw on that GHI why dashes are globally removed?

**Comment by garfield69** [comment]
>I mean it seems that replace will break every single group given every group and the naming standard is -Group.

don't we just need to add a replace ` Group` with `-Group` ?

>I may have missed it, but I'm don't think I saw on that GHI why dashes are globally removed?

I don't remember, my brain hurts. I'll take another look next time I'm free.

**Comment by garfield69** [comment]
@ilike2burnthing maybe could take a look into this, with a fresh set of eyes? Thanks.

**Comment by ilike2burnthing** [comment]
Something like this?

```text
      filters:
        - name: re_replace
          args: ["-([a-zA-Z]+)$", "~$1"]
        - name: re_replace
          args: ["-", " "]
        - name: re_replace
          args: ["~([a-zA-Z]+)$", "-$1"]
```

I'm about to fall asleep, so apologies that it's half-baked, e.g. it doesn't account for `-Group[TGx]` and the like.

**Comment by bakerboy448** [comment]
@ilike2burnthing do you have some time to test?  I think this should work

```yml
      filters:
        - name: re_replace
          args: ["-([\w]+(?:[\[\]\(\)\w]+)?)$", "~$1"]
        - name: re_replace
          args: ["-", " "]
        - name: re_replace
          args: ["~([\w]+(?:[\[\]\(\)\w]+)?)$", "-$1"]
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/commit/e39f0c115e142e120d89d4d9434a7ead420cc48e

**Comment by dombalaz** [comment]
Any help on getting this done also for thesceneplace? I am getting results with release group without "-" and I am struggling to get it work by myself.

**Comment by bakerboy448** [comment]
> https://github.com/Jackett/Jackett/commit/e39f0c115e142e120d89d4d9434a7ead420cc48e

@ilike2burnthing sceneplace as well?

Probably should check and see what other sites are removing `-`

**Comment by ilike2burnthing** [comment]
Unfortunately that results in `-​D Z0N3`, as the latter `-` gets replaced with a space, and so the release group is seen as `D`. I can't see an easy solution to that.

thesceneplace is a little different, they just completely screw with their titles, e.g.: `DOTA: Dragon's Blood S03 720p NF WEB DL DD+ 5 1 H 264 SMURF`

We could do an optional re_replace that just assumes the last word of all titles is the release group, e.g.: `["(\\w+)\\s(\\w+)$", "$1-$2"]`

It's fine for nearly all movies and TV, most game, some audio, and basically no book titles (hence the need to make it optional).
