### ISSUE TITLE
[BUG]: YggTorrent changed URL

### ISSUE THREAD

**Issue by Mouton99** [Prowlarr/Indexers#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

YggTorrent and YggCookie indexers use `www4.yggtorrent.li` base URL.

### Expected Behavior

YggTorrent and YggCookie indexers use `www3.yggtorrent.nz` base URL.

### Environment

```markdown
N/A
```

### What branch are you running?

Develop

### Anything else?

N/A

[AB#1415](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1415)

[AB#1416](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1416)

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Indexers/commit/197fb86bea13a9e8f0f233681021acd61a5e5562

covered under #15
