### ISSUE TITLE
Nyaa.si Support for RawSearch

### ISSUE THREAD

**Issue by dotzeno** [Prowlarr/Indexers#186]
[AB#3114](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3114)

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Indexers/commit/025d2e9f054fa4cf61367884a52f4d1967f4cb76

**Comment by Avamander** [comment]
I think I've stumbled upon searches where including non-alphanumeric characters results in zero results.

Is there a way to run these queries with both (or using the documented `|` syntax)?

**Comment by bakerboy448** [comment]
Please use [Discord](https://prowlarr.com/discord) for support/questions.
