### ISSUE TITLE
[broadcity] (updating) Login failed: Selector "a[href*="/logout.php?logouthash="]" didn't match

### ISSUE THREAD

**Issue by KyleSanderson** [Prowlarr/Indexers#193]
[BroadCity.txt](https://github.com/Prowlarr/Indexers/files/8693650/BroadCity.txt)

[AB#3145](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3145)

**Comment by bakerboy448** [comment]
Has this been fixed with the various YML updates and prowlarr updates?

**Comment by KyleSanderson** [comment]
No.

**Comment by bakerboy448** [comment]
Can you get fresh logs with the current dev 0.4.2.1879  or better yet nightly (0.4.3)?

**Comment by bakerboy448** [comment]
Closing; can reopen if this is reported as an issue and fresh logs are provided
