### ISSUE TITLE
Animeworld.cx - Missing array number of the categories in search query

### ISSUE THREAD

**Issue by Ben-Wallner** [Prowlarr/Indexers#196]
Prowlarr is currently missing the array number of the categories when searching and is thus not returning the results

Currently (wrong): 
`https://animeworld.cx/api/torrents/filter?api_token=(removed)&name=Fullmetal+Alchemist+Brotherhood+S01&categories[]=9&categories[]=14&categories[]=2&sortField=created_at&sortDirection=desc&perPage=100&page=1`

Fixed Version:
`https://animeworld.cx/api/torrents/filter?api_token=(removed)&name=Fullmetal+Alchemist+Brotherhood+S01&categories[0]=9&categories[1]=14&categories[2]=2&sortField=created_at&sortDirection=desc&perPage=100&page=1`

The animeworld definitons:
[v3](https://github.com/Prowlarr/Indexers/blob/835aeaaac613e399c0af5c916f4eea6c27f61fc8/definitions/v3/animeworld-api.yml)
[v4](https://github.com/Prowlarr/Indexers/blob/835aeaaac613e399c0af5c916f4eea6c27f61fc8/definitions/v4/animeworld-api.yml)
[v5](https://github.com/Prowlarr/Indexers/blob/dadb7e3acca07b871308dede8e022a61d273820d/definitions/v5/animeworld-api.yml)

[AB#3207](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3207)

**Comment by bakerboy448** [comment]
@garfield69 isn't this just standard unit3d? seems like Animeworld is running a custom flavor since the current search path seems consistent with the other unit3d trackers?

**Comment by garfield69** [comment]
>isn't this just standard unit3d? seems like Animeworld is running a custom flavor since the current search path seems consistent with the other unit3d trackers?

None of the Jackett team have an account for this indexer so we cannot verify independently.
The login page for the site does present a unit3d 6.0.0 page
If the site admin have changed the API to require category array indexing for a list of cats on the query, then that is a customisation, since the standard unit3d (up to v6.1.0) does not use this.
It should be noted that the current Jackett cardigann processor can not support that customisation currently.

**Comment by bakerboy448** [comment]
@Ben-Wallner - can you reach out to staff and find out?

**Comment by garfield69** [comment]
I have done some testing, and it appears that both 5.3.0 (brsociety) and 6.1.0 (generationfree) and 6.1.1b (blutopia) all accept using an index on the categories API query parm.
I've added support to the Jackett's Cardigann for this feature, by extending the Range statement to support the use of `[*]` to indicate that Cardigann should replace the asterisk with an incremental index beginning with zero.
See https://github.com/Jackett/Jackett/issues/13280 for details.

**Comment by Qstick** [comment]
Fixed in next nightly with v6 push
