### ISSUE TITLE
Update Portugas indexer

### ISSUE THREAD

**Issue by Norin-Radd** [Prowlarr/Indexers#254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Portugas indexer was updated to api on jackett

### Describe the solution you'd like

indexer being updated

### Describe alternatives you've considered

updating indexer

### Anything else?

not needed

[AB#3736](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3736)

[AB#3737](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3737)

**Comment by bakerboy448** [comment]
Closing in favor of #255
