### ISSUE TITLE
Unknown audio for AudioBookBay

### ISSUE THREAD

**Issue by lsaadeh** [Prowlarr/Indexers#269]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

![image](https://user-images.githubusercontent.com/43462320/204898867-4e313748-18e6-43b9-b6b2-05874ba27872.png)

### Expected Behavior

Match audio per site format details i.e. format = m4b https://audiobookbay.fi/audio-books/reminders-of-him-colleen-hoover/

### Steps To Reproduce

download book from audiobook bay

### Environment

```markdown
- OS: Ubuntu 20.04
- Prowlarr: 0.4.9.2083-ls75 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser:
```

### What branch are you running?

Master

### Trace Logs?

`2022-12-01 07:11:20.4|Info|ReleaseSearchService|Searching indexer(s): [AudioBookBay] for Term: [Colleen Hoover Reminders of Him], Offset: 0, Limit: 100, Categories: [3030]
2022-12-01 07:11:20.4|Info|Cardigann|Adding request: https://audiobookbay.fi/?s=Colleen%20Hoover%20Reminders%20of%20Him
2022-12-01 07:11:24.6|Info|Cardigann|Adding request: https://audiobookbay.fi/page/2/?s=Colleen%20Hoover%20Reminders%20of%20Him`

[AB#4244](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4244)

[AB#4255](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4255)

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Indexers/commit/b0ec4df774e9b4677b26d1df9c9e2e479795c64b
