### ISSUE TITLE
Adding Turktorrent as indexer to Prowlarr

### ISSUE THREAD

**Issue by UltraDavinci** [Prowlarr/Indexers#283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello everyone,

The last couple of days i've been trying to connect Turktorrent as indexer for Prowlarr, with no success so far. I've done all steps stated on Prowlarr.

This is the error Prowlarr is giving me: 

![Screenshot 2022-12-16 at 15 36 48](https://user-images.githubusercontent.com/120571937/208121684-09d8930d-4088-4cf1-b9dd-7768ba3c1b36.png)

I've no clue what else i could try, could someone help me?

### Expected Behavior

I expect TurkTorrent to connect as an indexer after i've logged in on the Turktorrent website and have pasted the request header cookies.

### Environment

```markdown
- OS: ubuntu 20.04
- Prowlarr: latest
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: chrome
```

### What branch are you running?

Master

### Trace Logs?

[prowlarr.trace.txt](https://github.com/Prowlarr/Indexers/files/10246706/prowlarr.trace.txt)

[AB#4476](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4476)

**Comment by bakerboy448** [comment]
Those are not logs those are just some HTML.

looks like you tried to save the page instead of copying the logs or something?

**Comment by UltraDavinci** [comment]
I'm sorry i uploaded the wrong file. Here is the correct file:
[prowlarr.trace.txt](https://github.com/Prowlarr/Indexers/files/10246967/prowlarr.trace.txt)

**Comment by bakerboy448** [comment]
```
<div id="content" class="mainContent fullwidth"> <div class="error" id="show_error">
<b>Bir Hata OluÅŸtu!</b><br />Bu sayfayÄ± gÃ¶rÃ¼ntÃ¼lemek iÃ§in veya bu iÅŸlemi gerÃ§ekleÅŸtir iÃ§in yetkiniz yok (Kullanici grubunuz yetmiyor olabilir, KULLANICI TURLERINI inceleyin anasayfadan!).
</div><div class="widget">
```
?

**Comment by UltraDavinci** [comment]
Works on my side. Those are Turkish unique characters 

<img width="1347" alt="Screenshot 2022-12-16 at 16 55 01" src="https://user-images.githubusercontent.com/120571937/208137599-cea72377-1685-434d-a090-16f95e6b80b5.png">

**Comment by bakerboy448** [comment]
It's part of an error block the site is returning....

**Comment by UltraDavinci** [comment]
Oh i see, thanks! I'll have contact with the developers on the Turktorrent side

**Comment by Qstick** [comment]
Seems to roughly translate to

```
An Error Occurred!
You do not have permission to view this page or perform this operation (Your user group may not be enough, check USER TYPES from the homepage!
```

**Comment by UltraDavinci** [comment]
I've come to the conclusion that my seedbox prowlarr instance that is running in docker won't accept the cookie because its a different IP address. I tried installing prowlarr locally and adding the indexer went perfectly.

Does anyone have thoughts on a fix? I've already tried using a vpn to my seedbox

**Comment by bakerboy448** [comment]
Closing then; not a prowlarr error.

Most sites allow you to report your seedbox ip so they don't block it, but that'll be a question for your site for how they expect users to use automation apps from seedboxes.
