### ISSUE TITLE
TheScenePlace parses size wrong (0B)

### ISSUE THREAD

**Issue by d3mystified** [Prowlarr/Indexers#287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Any search on TheScenePlace returns 0B size for results:

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/121274989/209270273-8c28c71b-4de6-4cba-9e47-89acd02616af.png">

### Expected Behavior

Correct size should be reported

### Steps To Reproduce

1. Add TSP
2. Search

### Environment

```markdown
- OS: Ubuntu 20.04
- Prowlarr: 0.4.11.2143
- Docker Install: 0.4.11.2143-ls79 by linuxserver.io
- Using Reverse Proxy: No
- Browser: Brave/Chrome
```

### What branch are you running?

Master

### Trace Logs?

https://gist.github.com/xBLACKHATx/18e997bbc808046760e571c1f5a8dd47

The main error:

```
2022-12-22 20:21:48.8|Trace|Cardigann|Error while parsing field=size, selector=td:has(a[href^="download.php?id="]) ~ td ~ td ~ td ~ td ~ td{{ if .Result._uploader }} ~ td{{ else }}{{ end }}, value=<null>: The string did not match the expected pattern.
```

Correct size is here:

```
<td align="center" width="30" class="lista">3.07 GB</td>
```

**Comment by bakerboy448** [comment]
@ilike2burnthing @garfield69 you guys have this issue in your side as well?

**Comment by garfield69** [comment]
>you guys have this issue in your side as well?

nope. here's the torrent the OP reported that Jackett returns:
![image](https://user-images.githubusercontent.com/6933240/210038891-c274eb63-7e60-4277-8a8d-34ba4960bef5.png)

**Comment by garfield69** [comment]
I expect this has been fixed in Prowlarr two days ago with https://github.com/Prowlarr/Prowlarr/pull/1264

**Comment by bakerboy448** [comment]
Needs https://github.com/Jackett/Jackett/commit/9490a8382f1c841f5c5138fc5b8182d1fafb8ded

For the title fix.

It'll be covered under the next jackett def pull.

Closing as the size is fixed

**Comment by bakerboy448** [comment]
Name fix
https://github.com/Prowlarr/Indexers/commit/f79e39d60a10db4990eb2fc2ae6dc3c49691b7d8
