### ISSUE TITLE
Siambit unable to download torrent

### ISSUE THREAD

**Issue by showkubii** [Prowlarr/Indexers#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://www.siambit.me/ajax.php?ction=say_thanks&id=

### Expected Behavior

https://www.siambit.me/ajax.php?action=say_thanks&id=

### Environment

```markdown
- OS: Unraid
- Prowlarr: 1.0.0.2201
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Google Chrome 108
```

### What branch are you running?

Nightly

### Trace Logs?
https://gist.github.com/showkubii/abc80a2e747a554c9d08eb06e3e08951

[AB#4594](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4594)

**Comment by showkubii** [comment]
> Are you using a custom cardigann definition somehow?
> 
> Because the definition it's surely using `action`.
> 
> https://github.com/Prowlarr/Indexers/blob/f79e39d60a10db4990eb2fc2ae6dc3c49691b7d8/definitions/v7/siambit.yml#L109-L118

no using a custom cardigann

**Comment by Qstick** [comment]
Wonder if this is acting up somehow.. it's the only way I see a initial char getting dropped

https://github.com/Prowlarr/Prowlarr/blob/43f4899324a7e07846bd2219183ab3532c0a433d/src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs#L722

**Comment by Qstick** [comment]
https://github.com/Prowlarr/Prowlarr/commit/858415b037b61fc15a1881e34f63b55711b3adeb

**Comment by showkubii** [comment]
> [Prowlarr/Prowlarr@858415b](https://github.com/Prowlarr/Prowlarr/commit/858415b037b61fc15a1881e34f63b55711b3adeb)

The problem persists

https://gist.github.com/showkubii/c3058953ba1894aea4ad35ba98d3270d

**Comment by Qstick** [comment]
That's really the only thing that would have chopped a character off the query string like that.

**Comment by showkubii** [comment]
> That's really the only thing that would have chopped a character off the query string like that.

No matter how I searched, I couldn't download the torrent.

Current Behavior
https://www.siambit.me/ajax.php?ction=say_thanks&id=

Expected Behavior
https://www.siambit.me/ajax.php?action=say_thanks&id=

**Comment by Qstick** [comment]
Positive you are on updated version?

**Comment by showkubii** [comment]
> Positive you are on updated version?

Prowlarr 1.0.0.2207

![image](https://user-images.githubusercontent.com/52117480/210157895-8a0331ff-6968-4b50-a9da-c56d29d5de86.png)

**Comment by Qstick** [comment]
> > Positive you are on updated version?
> 
> It works, I'm sorry, I forgot to press the check update button again on unraid.
> 
> T-T

No problem, thanks for reporting this.
