### ISSUE TITLE
Can't add brasiltracker

### ISSUE THREAD

**Issue by jaum20** [Prowlarr/Indexers#336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

error 'Unable to connect to indexer. We are being redirected to the login page. Most likely your session expired or was killed. Recheck your cookie or credentials and try testing the indexer'. The credentials are right. They (brasiltracker) had a data leak recently and asked the users to change password, what I did. Since then I can't make the indexer to work with Prowlarr

### Expected Behavior

Add the indexer to prowlarr

### Steps To Reproduce

1. click add indexer
2. search for brasiltracker
3. fill credentials and click test or save
4. error

### Environment

```markdown
- OS: ubuntu 18 bionic
- Prowlarr: 1.4.1.3258
- Docker Install: no
- Using Reverse Proxy: no
- Browser: Brave
```

### What branch are you running?

Master

### Trace Logs?

[prowlarr.trace (2).txt](https://github.com/Prowlarr/Indexers/files/11481429/prowlarr.trace.2.txt)

[AB#4911](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4911)

**Comment by bakerboy448** [comment]
Seems they've added a post-login captcha to fight against automation tools.

**Comment by ikki4** [comment]
I said it on Discord and I'll say it here too. If you guys know what to do to fix this issue, but you can't do it without an invite to BrasilTracker, please dm me your email address and I'll try to reach out the tracker's admins to see if they can put you in.

**Comment by ilike2burnthing** [comment]
Oh, my bad, I missed the `invite needed` label. Bogdan, if you're free some time to work on this, let me know and I'll throw you my credentials.
