### ISSUE TITLE
Anthelion: Unable to connect to indexer. Unexpected response status InternalServerError code from indexer request

### ISSUE THREAD

**Issue by jaum20** [Prowlarr/Indexers#339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When adding anthelion indexer, it gives the error: Unable to connect to indexer. Unexpected response status InternalServerError code from indexer request. The traker is on.

### Expected Behavior

add the tracker

### Steps To Reproduce

1. Add Indexer
2. anthelion
3. fill in api key
4. save
5. error

### Environment

```markdown
- OS: Ubuntu 18
- Prowlarr: 1.5.2.3484
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Brave
```

### What branch are you running?

Master

### Trace Logs?

[prowlarr.trace.txt](https://github.com/Prowlarr/Indexers/files/11664864/prowlarr.trace.txt)

**Comment by bakerboy448** [comment]
Appears anthelion made a material breaking change to their api?

**Comment by jaum20** [comment]
This may be a problem with anthelion itself. Just found that anthelion.me/torrents.php is showing HTTP ERROR 500
