### ISSUE TITLE
 broken indexers :  https://www.icc2022.com/

### ISSUE THREAD

**Issue by fishredleung** [Prowlarr/Indexers#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It has changed its ui and the login form in the Prowlarr data base was no longer working , many thanks

### Expected Behavior

Prowlarr idendify the new login in form and be able to fill in the information correctly

### Environment

```markdown
- OS: Synology
- Prowlarr: 1.6.3.3608
- Docker Install: yes
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Master

### Trace Logs?

.

**Comment by ilike2burnthing** [comment]
Working fine here, in Prowlarr and Jackett. Are you completing the captcha when reconfiguring the indexer, and entering credentials manually (not autofill)?

**Comment by fishredleung** [comment]
please see the error shown below when I try to set up for Icc2002:
`Unable to connect to indexer, check the log above the ValidationFailure for more details. Login failed: No form found on https://www.icc2022.com/login.php using form selector form[action="takelogin.php"]`

**Comment by ilike2burnthing** [comment]
Answer the question above.

If the answer to both parts is yes, provide the trace log for the issue.

**Comment by fishredleung** [comment]
> 

Yes , manually.
please find the trace log here: https://drive.google.com/file/d/1hqFhI5p0UWQuYPuctbhqa1lUfEFWzWEv/view?usp=sharing

**Comment by ilike2burnthing** [comment]
> Login lock! (Maximum number of authentication error attempts Login times have arrived)
We suspect that you are spoofing the system and therefore disable your IP address!

Your IP has been blocked. If you're using a proxy or VPN, change the server; if you're using a VPS or seedbox, you may need to use a proxy or VPN, or get in contact with the tracker's admins.

You also have a lot of errors for HDArea that I'll get back to you about shortly.

**Comment by fishredleung** [comment]
> > Login lock! (Maximum number of authentication error attempts Login times have arrived)
> > We suspect that you are spoofing the system and therefore disable your IP address!
> 
> Your IP has been blocked. If you're using a proxy or VPN, change the server; if you're using a VPS or seedbox, you may need to use a proxy or VPN, or get in contact with the tracker's admins.
> 
> You also have a lot of errors for HDArea that I'll get back to you about shortly.

If I try to connect the website manually by using chrome brower, I can log in to the website, I will try to switch an other IP later and let you know the result.

**Comment by ilike2burnthing** [comment]
Are your browser and Prowlarr using the same IP (e.g. no proxies or VPNs, on the same network)?

**Comment by fishredleung** [comment]
> Are your browser and Prowlarr using the same IP (e.g. no proxies or VPNs, on the same network)?

Yes , same IP and same machine, also , when I use other tools(NAS tools)  to manage the PT site, it is working fine.

**Comment by ilike2burnthing** [comment]
As a test:
1. install Prowlarr on a computer and see if you get the same error
2. install Jackett on your Synology and see if you get the same error

**Comment by fishredleung** [comment]
Prowlarr works fine at the PC with another IP, I believe the problem was mine. I will try to switch to another IP tonight and see if the problem is solved , many thanks to your help.

**Comment by bakerboy448** [comment]
Any updates?

**Comment by fishredleung** [comment]
> Any updates?

The indexer is now working correctly , appreciately your help.
