### ISSUE TITLE
YGGtorrent: new URL

### ISSUE THREAD

**Issue by w0rd3r** [Prowlarr/Indexers#448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

YGGTorrent is on https://yggtorrent.cool/, today (17/05/2024) they changed to a new domain name https://ygg.re.

Is it possible for you to update the URL?

Thanks in advance

### Expected Behavior

Correct URL

### Steps To Reproduce

-

### Environment

```markdown
- OS:
- Prowlarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

-

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by SadE54** [comment]
Another point is that the indexer became private, with direct login on the main page.
Possibly , cloudflare is not used anymore at this time

**Comment by Dranaxele** [comment]
![image](https://github.com/Prowlarr/Indexers/assets/8998026/01477701-da57-4268-942b-580f55bdbaa9)
Got this following error when testing connection.

**Comment by gromez** [comment]
I don't think only changing the URL will work, all the login process must be updated for the new auth page: https://www.ygg.re/auth/login

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Indexers/commit/27e3937ac706e59bc096fe1761a82970b5d06b1f

**Comment by meyverick** [comment]
Is it fixed? I don't manage to make it works again.

**Comment by bakerboy448** [comment]
Please use [Discord](https://prowlarr.com/discord) for support/questions.
