### ISSUE TITLE
MegaPeer: Unable to connect to indexer. Unexpected response status Forbidden code from indexer request

### ISSUE THREAD

**Issue by soredake** [Prowlarr/Indexers#462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`Unable to connect to indexer. Unexpected response status Forbidden code from indexer request`

### Expected Behavior

Should work fine, like in Jackett.

### Steps To Reproduce

1. Setup prowlarr in docker.
2. Try to add MegaPeer indexer.
3. Error!!!

### Environment

```markdown
- OS: Ubuntu 22.04
- Prowlarr: 1.18.0.4543
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: 126.0.1
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[prowlarr.trace.txt](https://github.com/user-attachments/files/15809836/prowlarr.trace.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Logs not currently accessible due to GitHub https issues but this _may_ be a support issue

**Comment by bakerboy448** [comment]
Contact the tracker for assistance in why Prowlarr's request is being responded with forbidden

**Comment by ilike2burnthing** [comment]
Site is blocking Prowlarr UA.
