### ISSUE TITLE
asiancinema.me has changed its url.

### ISSUE THREAD

**Issue by Zer0Lyfe** [Prowlarr/Indexers#472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Prowlarr current URL is the previous URL that was being used being asiancinema.me but now it is now known as eiga.moi

### Expected Behavior

For the URL to be updated

### Steps To Reproduce

Try go to the previous link and it will link to the new url

### Environment

```markdown
- OS: all
- Prowlarr: all
- Docker Install: both
- Using Reverse Proxy: both
- Browser: all
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

![Screenshot_20240630_151253_Brave](https://github.com/Prowlarr/Indexers/assets/28994351/b054b44d-c806-4fe5-b9e1-464c94d6c284)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Indexers/commit/ba0fe3067935ac3c0fcc048e20097a5a0201a8a3
