### ISSUE TITLE
[Speedapp] Unable to connect to indexer, check the log above the ValidationFailure for more details. HTTP request failed: [401:Unauthorized] [POST] at [https://speedapp.io/api/login]

### ISSUE THREAD

**Issue by jaum20** [Prowlarr/Indexers#473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Can't add Speedapp indexer

### Expected Behavior

Add Speedapp indexer

### Steps To Reproduce

1. Click speedapp indexer
2. enter email and password
3. Unable to connect to indexer, check the log above the ValidationFailure for more details. HTTP request failed: [401:Unauthorized] [POST] at [https://speedapp.io/api/login]

### Environment

```markdown
- OS:Debian 11 (bullseye)
- Prowlarr:1.19.0.4568
- Docker Install: yes
- Using Reverse Proxy: No
- Browser: Brave
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[prowlarr.trace.txt](https://github.com/user-attachments/files/16073089/prowlarr.trace.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by jaum20** [comment]
Sorry. Wrong credentials

**Comment by Liionboy** [comment]
> Sorry. Wrong credentials

And what credential you used? Because i have the same error and i don't know what to use
