### ISSUE TITLE
Adding Season information into Release Titles for Nyaa.si does not work

### ISSUE THREAD

**Issue by iFox11** [Prowlarr/Indexers#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The nyaa.si indexer has an option called **Improve Sonarr compatibility by trying to add Season information into Release Titles**.
When this is enabled it adds for example S1 to the Release Titles.

Before enabling:
![image](https://github.com/user-attachments/assets/e194ca39-535f-42ec-84b7-0d3db0e6f905)

After enabling:
![image](https://github.com/user-attachments/assets/e129f74e-320e-4b6f-a2a8-7571f80f5990)

The problem is that when I include S1 in the search I do not get any results.
![image](https://github.com/user-attachments/assets/c9604287-ea58-4028-8420-652a9219e9d9)

### Expected Behavior

After enabling **Improve Sonarr compatibility by trying to add Season information into Release Titles** I would expect that the search would include results with the added S1 part.
This would allow Sonarr to recognize Season packs that have only Season 1 in title and not S1.

### Steps To Reproduce

1. Enable **Improve Sonarr compatibility by trying to add Season information into Release Titles**
2. Search for [EMBER] Wistoria: Wand and Sword (2024) (Season 1) which returns releases with the added S1
3. Search for [EMBER] Wistoria: Wand and Sword (2024) (Season 1 S1) which does not returns any releases 

### Environment

```markdown
- OS: TrueNAS-SCALE-23.10.2
- Prowlarr: 1.24.3.4754-ls88 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome Version 130.0.6723.59
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[prowlarr.trace.txt](https://github.com/user-attachments/files/17420427/prowlarr.trace.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
For support and inquiries, please use our [Discord](http://prowlarr.com/discord) channel. GitHub is designated solely for bug reports and feature requests. It seems that this issue may fall under a support request, so we kindly ask you to visit our Discord for assistance. Thank you.

> Improve Sonarr compatibility by trying to add Season information into Release Titles

This impacts the returned titles and does not impact the search term
