### ISSUE TITLE
[bug] Redacted is back as redacted.sh

### ISSUE THREAD

**Issue by jaum20** [Prowlarr/Indexers#499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to connect to indexer, please check your DNS settings and ensure IPv6 is working or disabled. Name or service not known (redacted.ch:443

### Expected Behavior

connect to teh new domain redacted.sh

### Steps To Reproduce

Add redacted

### Environment

```markdown
- OS: debian 12 aarch64
- Prowlarr: 1.26.1.4844
- Docker Install: no
- Using Reverse Proxy: yes
- Browser: Brave
```

### What branch are you running?

Develop

### Trace Logs? **Not Optional**

Unable to connect to indexer, please check your DNS settings and ensure IPv6 is working or disabled. Name or service not known (redacted.ch:443

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Already fixed in nightly https://github.com/Prowlarr/Prowlarr/commit/b447db5d08f9fa0127570375efdee4478bbaee97
