### ISSUE TITLE
EZTV & 1337X Search Issues

### ISSUE THREAD

**Issue by ExorcistF1** [Prowlarr/Indexers#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

then search in sonarr for episode, 1337x don't give any results, EZTV bring back all new releases on tracker. 

### Expected Behavior

for Rarbg search works fine.

### Environment

```markdown
- OS: win 11
- Prowlarr: 0.1.6.1184
- Sonarr: 3.0.6.1390
- Docker Install:
- Using Reverse Proxy: 
- Browser:Microsoft Edge Version 96.0.1054.41
```

### What branch are you running?

Develop

### Trace Logs?

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/7648937/prowlarr.trace.txt)

[AB#2029](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2029)

[AB#2031](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2031)

**Comment by i-am-at0m** [comment]
This is either still an issue on Prowlarr or an issue again, for EZTV
