### ISSUE TITLE
No result on abn.lol search

### ISSUE THREAD

**Issue by jrozelle** [Prowlarr/Indexers#83]
Hello,

Current abnormal.yml definition do not give any result on search.

Log show correct URL, who gives expected resultats when copy/paste in a browser. It seems that reasults are not handled by Prowlarr.

Anybody can take a look ?

[AB#2114](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2114)

**Comment by bakerboy448** [comment]
Please open a bug report with the appropriate details on the main Prowlarr repository
