### ISSUE TITLE
No result on abn.lol search (Abnormal)

### ISSUE THREAD

**Issue by jrozelle** [Prowlarr/Indexers#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello
Radarr nor Sonarr give any result on abnormal (abn.lol, not "not normal" :D) search

Log show correct URL, who gives expected resultats when copy/paste in a browser. It seems that reasults are not handled by Prowlarr.

### Expected Behavior

Having search results

### Steps To Reproduce

1. Manuel search on Radarr or Sonarr

### Environment

```markdown
- OS: DSM 6.2.4
- Prowlarr: 0.1.7.1209
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser:
```

### What branch are you running?

Develop

### Trace Logs?

Nothing in logs, 0 error, even in trace mode :(

[AB#2119](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2119)

[AB#2121](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2121)

**Comment by bakerboy448** [comment]
@AthAshino can you take a look?

Note: I fixed a category typo here
https://github.com/Prowlarr/Indexers/pull/85/files

**Comment by AthAshino** [comment]
Hey jrozelle, thank you for reporting I hadn't noticed that and as a result I couldn't get anything back from ABN either.
They changed the search page, now there is one more column so the scrapping was deprecated. I changed that with my PR, hope it will be push soon so you can get results back

**Comment by jrozelle** [comment]
wow, this was quick, thank you ! @AthAshino

**Comment by jrozelle** [comment]
Here another (related) problem : results are not displayed in Radarr/Sonarr.

When I look traces and open URL requested, it gives me "api" file.

Same structure in the file, but 2 differences : 

```
<?xml version="1.0" encoding="UTF-8"?>
<rss version="1.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link rel="self" type="application/rss+xml" />
    <title>Prowlarr</title>
    <item>
      <title><movie title></title>
      <guid>https://abn.lol/Torrent/blabla</guid>
      <prowlarrindexer id="1">Abnormal</prowlarrindexer>
      <comments>https://abn.lol/Torrent/Details?ReleaseId=xxxxx</comments>
      <pubDate>Sat, 11 Dec 2021 </pubDate>
      <size>56049324032</size>
      **<link></link>**
      <category>2000</category>
      <category>100002</category>
      **<enclosure url="" length="56049324032" type="application/x-bittorrent" />**
      <torznab:attr name="category" value="2000" />
      <torznab:attr name="category" value="100002" />
      <torznab:attr name="tag" value="freeleech" />
      <torznab:attr name="rageid" value="0" />
      <torznab:attr name="tvdbid" value="0" />
      <torznab:attr name="imdb" value="0000000" />
      <torznab:attr name="tmdbid" value="0" />
      <torznab:attr name="seeders" value="6" />
      <torznab:attr name="peers" value="6" />
      <torznab:attr name="downloadvolumefactor" value="0" />
      <torznab:attr name="uploadvolumefactor" value="1" />
    </item>
```

"link" and "enclosure url" are empty. 

I think this is part of the problem
